
export const videos = [
    {
        img1: "play9.webp",
        img2: "play9logo.jpg",
        title: "Palagi - TJ Monterde | BEST OF WISH 107.5 Top Songs 2024 - Best OPM New Songs Playlist 2024",
        channel: "YouTube Vids",
        views: "30k",
        hours: "3 hours",
        duration: "02:12",
    },
    {
        img1: "play2.webp",
        img2: "play2&7logo.jpg",
        title: "Tadhana, Uhaw 🎵 Nonstop OPM Love Songs With Lyrics 2024 🎧 Soulful Tagalog Songs Of All Time Playlist",
        channel: "YouTube Vids",
        views: "30k",
        hours: "3 hours",
        duration: "02:12",
    },
    {
        img1: "play3.webp",
        img2: "play3logo.jpg",
        title: "Musics PH",
        channel: "YouTube Vids",
        views: "30k",
        hours: "3 hours",
        duration: "02:12",
    },
    {
        img1: "play4.webp",
        img2: "play4logo.jpg",
        title: "Tadhana, Sana 🎶LIVE on Wish 107.5 Bus Playlist 2024 With Lyrics - Best of Wish 107.5 Playlist",
        channel: "YouTube Vids",
        views: "30k",
        hours: "3 hours",
        duration: "02:12",
    },
    {
        img1: "play5.webp",
        img2: "play5logo.jpg",
        title: "Diwata Pares by Alex Gonzaga",
        channel: "YouTube Vids",
        views: "30k",
        hours: "3 hours",
        duration: "02:12",
    },
    {
        img1: "play6.webp",
        img2: "play6logo.jpg",
        title: "NewJeans (뉴진스) 'Bubble Gum' Official MV",
        channel: "YouTube Vids",
        views: "30k",
        hours: "3 hours",
        duration: "02:12",
    },
    {
        img1: "play7.webp",
        img2: "play2&7logo.jpg",
        title: "RAPSTAR x LAGABOG FLOW G PLAYLIST💥Tagalog Rap Songs Nonstop 2024 -- SKusta Clee, Flow G 2024 #top3",
        channel: "YouTube Vids",
        views: "30k",
        hours: "3 hours",
        duration: "02:12",
    },
    {
        img1: "play8.webp",
        img2: "play8logo.jpg",
        title: "#3 TIMBERWOLVES at #6 SUNS | FULL GAME 4 HIGHLIGHTS | April 28, 2024",
        channel: "YouTube Vids",
        views: "30k",
        hours: "3 hours",
        duration: "02:12",
    },
]